apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-auth
  template:
    metadata:
      labels:
        app: ticketing-auth
    spec:
      containers:
      - name: ticketing-auth
        image: armosdocker/ticketing-auth
        resources:
          limits:
            memory: "64Mi"
            cpu: "250m"

---
# Cluster Service

apiVersion: v1
kind: Service
metadata:
  name: ticketing-auth-srv
spec:
  selector:
    app: ticketing-auth
  ports:
  - name: ticketing-auth
    protocol: TCP
    port: 3000
    targetPort: 3000
