apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-client
  template:
    metadata:
      labels:
        app: ticketing-client
    spec:
      containers:
        - name: ticketing-client
          image: armosdocker/ticketing-client
          # Env variables
          env:
            - name: OKTETO_NAMESPACE
              valueFrom:
                configMapKeyRef:
                  name: ticketing-client
                  key: namespace
            - name: API_BASE_URL
              value: https://ingress-srv-ticketing-santhoshsonu.cloud.okteto.net

---
# Cluster Service

apiVersion: v1
kind: Service
metadata:
  name: ticketing-client-srv
spec:
  selector:
    app: ticketing-client
  ports:
    - name: ticketing-client
      protocol: TCP
      port: 3000
      targetPort: 3000
