apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticketing-tickets-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticketing-tickets
  template:
    metadata:
      labels:
        app: ticketing-tickets
    spec:
      containers:
        - name: ticketing-tickets
          image: armosdocker/ticketing-tickets
          imagePullPolicy: Always
          # Env variables
          env:
            # Provide pod name as env var
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NATS_URI
            - name: NATS_CLUSTER_ID
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: NATS_CLUSTER_ID
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: TICKET_MONGO_DB_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY # K8s secret key

---
# Cluster Service

apiVersion: v1
kind: Service
metadata:
  name: ticketing-tickets-srv
spec:
  selector:
    app: ticketing-tickets
  ports:
    - name: ticketing-tickets
      protocol: TCP
      port: 3000
      targetPort: 3000
